import Head from 'next/head';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Col, Row } from 'react-bootstrap';
import comingSoonimg from '../../public/images/comingsoon.png'
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h3 className='text-center py-4'>Welcome to DashBoard</h3>
        <section className='px-3'>
          <Row>
            <Col className='col-4 text-center'>
              <div className='border rounded-1 p-2 bg-primary'>
                <h6>Categories</h6>
                <p>45</p>
              </div>
            </Col>
            <Col className='col-4 text-center'>
              <div className='border rounded-1 p-2 bg-info'>
                <h6>Products</h6>
                <p>70</p>
              </div>
            </Col>
            <Col className='col-4 text-center'>
              <div className='border rounded-1 p-2 bg-danger'>
                <h6>Users</h6>
                <p>1</p>
              </div>
            </Col>
          </Row>
          <div className='text-center pt-5'>
            <Image src={comingSoonimg} alt='comingSoon Image'/>
          </div>
        </section>
      </main>
    </>
  )
}
